POST http://localhost:5001/api/user
Content-Type: application/json

{
    "name": "John",
    "email": "john@test.com"
}

###
GET http://localhost:5001/api/user
Content-Type: application/json

###
GET http://localhost:5001/api/user/1
Content-Type: application/json

###
PUT http://localhost:5001/api/user/1
Content-Type: application/json

{
    "name": "Johnny",
    "email": "john@test.com"
}

###
DELETE http://localhost:5001/api/user/1
Content-Type: application/json